/***********************************************************************************************************************
 * This file was generated by the MCUXpresso Config Tools. Any manual edits made to this file
 * will be overwritten if the respective MCUXpresso Config Tools is used to update this file.
 **********************************************************************************************************************/

#ifndef _CLOCK_CONFIG_H_
#define _CLOCK_CONFIG_H_

#include "fsl_common.h"

/*******************************************************************************
 * Definitions
 ******************************************************************************/
#define BOARD_XTAL0_CLK_HZ                         48000000U  /*!< Board xtal0 frequency in Hz */

/*******************************************************************************
 ************************ BOARD_InitBootClocks function ************************
 ******************************************************************************/

#if defined(__cplusplus)
extern "C" {
#endif /* __cplusplus*/

/*!
 * @brief This function executes default configuration of clocks.
 *
 */
void BOARD_InitBootClocks(void);

#if defined(__cplusplus)
}
#endif /* __cplusplus*/

/*******************************************************************************
 *************************** Configuration HSCLOCK *****************************
 ******************************************************************************/
/*******************************************************************************
 * Definitions for HSCLOCK configuration
 ******************************************************************************/
#define HSCLOCK_CORE_CLOCK                        228000000U  /*!< Core clock frequency: 228000000Hz */

/*! @brief MCG set for HSCLOCK configuration.
 */
extern const mcg_config_t mcgConfig_HSCLOCK;
/*! @brief SIM module set for HSCLOCK configuration.
 */
extern const sim_clock_config_t simConfig_HSCLOCK;
/*! @brief OSC set for HSCLOCK configuration.
 */
extern const osc_config_t oscConfig_HSCLOCK;

/*******************************************************************************
 * API for HSCLOCK configuration
 ******************************************************************************/
#if defined(__cplusplus)
extern "C" {
#endif /* __cplusplus*/

/*!
 * @brief This function executes configuration of clocks.
 *
 */
void HSCLOCK(void);

#if defined(__cplusplus)
}
#endif /* __cplusplus*/

#endif /* _CLOCK_CONFIG_H_ */

